# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(777, 600)
        MainWindow.setMinimumSize(QtCore.QSize(777, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(560, 20, 201, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(560, 230, 201, 191))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(340, 20, 201, 191))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_adminMenu = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_adminMenu.setContentsMargins(0, 0, 0, 0)
        self.formLayout_adminMenu.setObjectName("formLayout_adminMenu")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(340, 230, 201, 191))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.iueWidget = QtWidgets.QWidget(self.formLayoutWidget_4)
        self.iueWidget.setObjectName("iueWidget")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iueWidget)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 311, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_company = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_company.setObjectName("pushButton_company")
        self.verticalLayout.addWidget(self.pushButton_company)
        self.pushButton_staff = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_staff.setObjectName("pushButton_staff")
        self.verticalLayout.addWidget(self.pushButton_staff)
        self.pushButton_products = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_products.setObjectName("pushButton_products")
        self.verticalLayout.addWidget(self.pushButton_products)
        self.pushButton_logout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.verticalLayout.addWidget(self.pushButton_logout)
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(339, 430, 421, 151))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 230, 311, 351))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_company.setText(_translate("MainWindow", "Settings"))
        self.pushButton_staff.setText(_translate("MainWindow", "Staff"))
        self.pushButton_products.setText(_translate("MainWindow", "Products"))
        self.pushButton_logout.setText(_translate("MainWindow", "Logout"))
