# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WorkAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 662)
        MainWindow.setMinimumSize(QtCore.QSize(1261, 606))
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    color: white;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"QLineEdit:disabled\n"
"{\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_worktype = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_worktype.setMaximumSize(QtCore.QSize(16777215, 75))
        self.comboBox_worktype.setObjectName("comboBox_worktype")
        self.comboBox_worktype.addItem("")
        self.comboBox_worktype.addItem("")
        self.gridLayout.addWidget(self.comboBox_worktype, 0, 1, 1, 1)
        self.label_worktype = QtWidgets.QLabel(self.centralwidget)
        self.label_worktype.setMinimumSize(QtCore.QSize(100, 0))
        self.label_worktype.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_worktype.setFont(font)
        self.label_worktype.setObjectName("label_worktype")
        self.gridLayout.addWidget(self.label_worktype, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_staffid = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_staffid.setFont(font)
        self.label_staffid.setObjectName("label_staffid")
        self.gridLayout_2.addWidget(self.label_staffid, 0, 0, 1, 1)
        self.label_staffname = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_staffname.setFont(font)
        self.label_staffname.setObjectName("label_staffname")
        self.gridLayout_2.addWidget(self.label_staffname, 0, 1, 1, 1)
        self.label_staffmail = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_staffmail.setFont(font)
        self.label_staffmail.setObjectName("label_staffmail")
        self.gridLayout_2.addWidget(self.label_staffmail, 0, 2, 1, 1)
        self.lineEdit_staffid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_staffid.setEnabled(False)
        self.lineEdit_staffid.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_staffid.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_staffid.setObjectName("lineEdit_staffid")
        self.gridLayout_2.addWidget(self.lineEdit_staffid, 1, 0, 1, 1)
        self.lineEdit_staffname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_staffname.setEnabled(False)
        self.lineEdit_staffname.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_staffname.setObjectName("lineEdit_staffname")
        self.gridLayout_2.addWidget(self.lineEdit_staffname, 1, 1, 1, 1)
        self.lineEdit_staffmail = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_staffmail.setEnabled(False)
        self.lineEdit_staffmail.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_staffmail.setObjectName("lineEdit_staffmail")
        self.gridLayout_2.addWidget(self.lineEdit_staffmail, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_productpiece = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_productpiece.setFont(font)
        self.label_productpiece.setObjectName("label_productpiece")
        self.gridLayout_3.addWidget(self.label_productpiece, 0, 2, 1, 1)
        self.lineEdit_productname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_productname.setEnabled(False)
        self.lineEdit_productname.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_productname.setObjectName("lineEdit_productname")
        self.gridLayout_3.addWidget(self.lineEdit_productname, 1, 1, 1, 1)
        self.label_productid = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_productid.setFont(font)
        self.label_productid.setObjectName("label_productid")
        self.gridLayout_3.addWidget(self.label_productid, 0, 0, 1, 1)
        self.label_productname = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_productname.setFont(font)
        self.label_productname.setObjectName("label_productname")
        self.gridLayout_3.addWidget(self.label_productname, 0, 1, 1, 1)
        self.lineEdit_productid = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_productid.setEnabled(False)
        self.lineEdit_productid.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_productid.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.lineEdit_productid.setObjectName("lineEdit_productid")
        self.gridLayout_3.addWidget(self.lineEdit_productid, 1, 0, 1, 1)
        self.spinBox_productpiece = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_productpiece.setMinimumSize(QtCore.QSize(125, 0))
        self.spinBox_productpiece.setObjectName("spinBox_productpiece")
        self.gridLayout_3.addWidget(self.spinBox_productpiece, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_4.addWidget(self.pushButton_add, 3, 0, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_4.addWidget(self.pushButton_confirm, 6, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_tablestaff = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_tablestaff.setFont(font)
        self.label_tablestaff.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tablestaff.setObjectName("label_tablestaff")
        self.gridLayout_5.addWidget(self.label_tablestaff, 0, 0, 1, 1)
        self.label_tableproduct = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_tableproduct.setFont(font)
        self.label_tableproduct.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tableproduct.setObjectName("label_tableproduct")
        self.gridLayout_5.addWidget(self.label_tableproduct, 0, 1, 1, 1)
        self.tableWidget_staff = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_staff.setMinimumSize(QtCore.QSize(351, 451))
        self.tableWidget_staff.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget_staff.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_staff.setProperty("showDropIndicator", True)
        self.tableWidget_staff.setAlternatingRowColors(False)
        self.tableWidget_staff.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_staff.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_staff.setRowCount(0)
        self.tableWidget_staff.setObjectName("tableWidget_staff")
        self.tableWidget_staff.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_staff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_staff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_staff.setHorizontalHeaderItem(2, item)
        self.tableWidget_staff.horizontalHeader().setCascadingSectionResizes(True)
        self.gridLayout_5.addWidget(self.tableWidget_staff, 1, 0, 1, 1)
        self.tableWidget_product = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_product.setMinimumSize(QtCore.QSize(351, 451))
        self.tableWidget_product.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tableWidget_product.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_product.setProperty("showDropIndicator", True)
        self.tableWidget_product.setAlternatingRowColors(False)
        self.tableWidget_product.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_product.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_product.setRowCount(0)
        self.tableWidget_product.setObjectName("tableWidget_product")
        self.tableWidget_product.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_product.setHorizontalHeaderItem(2, item)
        self.tableWidget_product.horizontalHeader().setCascadingSectionResizes(True)
        self.gridLayout_5.addWidget(self.tableWidget_product, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 1, 7, 1)
        self.tableWidget_selectproduct = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_selectproduct.setObjectName("tableWidget_selectproduct")
        self.tableWidget_selectproduct.setColumnCount(3)
        self.tableWidget_selectproduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_selectproduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_selectproduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_selectproduct.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tableWidget_selectproduct, 4, 0, 1, 1)
        self.tableWidget_selectstaff = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_selectstaff.setObjectName("tableWidget_selectstaff")
        self.tableWidget_selectstaff.setColumnCount(3)
        self.tableWidget_selectstaff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_selectstaff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_selectstaff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_selectstaff.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.tableWidget_selectstaff, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1278, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_worktype.setItemText(0, _translate("MainWindow", "Work Type1"))
        self.comboBox_worktype.setItemText(1, _translate("MainWindow", "Work Type2"))
        self.label_worktype.setText(_translate("MainWindow", "Work Type"))
        self.label_staffid.setText(_translate("MainWindow", "Staff ID"))
        self.label_staffname.setText(_translate("MainWindow", "Staff Name"))
        self.label_staffmail.setText(_translate("MainWindow", "Staff Email"))
        self.label_productpiece.setText(_translate("MainWindow", "Product Piece"))
        self.label_productid.setText(_translate("MainWindow", "Product ID"))
        self.label_productname.setText(_translate("MainWindow", "Product Name"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_tablestaff.setText(_translate("MainWindow", "STAFF"))
        self.label_tableproduct.setText(_translate("MainWindow", "PRODUCTS"))
        self.tableWidget_staff.setSortingEnabled(False)
        item = self.tableWidget_staff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_staff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yeni Sütun"))
        item = self.tableWidget_staff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        self.tableWidget_product.setSortingEnabled(False)
        item = self.tableWidget_product.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_product.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_product.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Piece"))
        item = self.tableWidget_selectproduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidget_selectproduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.tableWidget_selectproduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Product Piece"))
        item = self.tableWidget_selectstaff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Staff ID"))
        item = self.tableWidget_selectstaff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Staff Name"))
        item = self.tableWidget_selectstaff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Staff Email"))
